# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # [Keep all these as they serve different purposes than linting]
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-symlinks
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: |
          (?x)(
              ^example/large/file.csv|
              ^example/large/sklearn-model.pkl
          )
      - id: requirements-txt-fixer
      - id: forbid-new-submodules
      - id: detect-private-key

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.12.0"
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --config=./pyproject.toml]
      - id: ruff-format

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.7
    hooks:
      - id: pylint
        args:
          - --rcfile=./pyproject.toml
